name: Run Pytest
on: [pull_request]
jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Set env
        run: echo "False" >> $FULL_PATH

      - name: Run tests
        run: uv run pytest tests
